[#ftl]
[#assign IpInstance = ""]
[#assign ExtiLine = ""]
[#assign IrqNumber = ""]
[#assign IpName = ""]


[#assign BCD_PORT = ""]
[#assign BCD_PIN = ""]
[#assign BCD_IRQn = ""]
[#assign BCD_EXTI = ""]
[#assign useBCD = false]
[#compress]
[#if BspIpDatas??]
[#list BspIpDatas as SWIP] 
	[#if SWIP.variables??]
		[#list SWIP.variables as variables]
			[#if variables.name?contains("IpInstance")]
				[#assign IpInstance = variables.value]
			[/#if]		
			[#if variables.name?contains("GPIO_INT_NUM")]
				[#assign IrqNumber = variables.value]				
			[/#if]	
			[#if variables.name?contains("IpName")]
				[#assign IpName = variables.value]				
			[/#if]					
			[#if variables.name?contains("EXTI_LINE_NUMBER")]
				[#assign ExtiLine = variables.value]
			[/#if]
			[#if variables.value?contains("BCD Detection")]							
				[#assign BCD_EXTI = ExtiLine]
				[#assign BCD_PORT = IpName]
				[#assign BCD_PIN  = IpInstance]
				[#assign BCD_IRQn = IrqNumber]	
				[#assign useBCD = true]				
			[/#if]	
		[/#list]
	[/#if]
[/#list]
[/#if]
[/#compress]
#tif (HAL_GPIO_ReadPin(${BCD_PORT}, ${BCD_PIN}) == GPIO_PIN_SET)
