[#ftl]
[#compress]
[#assign threadControlBlock = "NULL"]
[#assign mutexControl       = "NULL"]
[#assign timerControlBlock  = "NULL"]
[#assign queueControlBlock  = "NULL"]
[#assign semaphoreControl   = "NULL"]
[#assign eventControl       = "NULL"]
[#assign generateStaticTask  = "no"]
[#assign generateStaticQueue = "no"]
[#assign generateStaticTimer = "no"]
[#assign generateStaticMutex = "no"]
[#assign generateStaticSemaphore = "no"]
[#assign generateStaticEvent = "no"]

[#-- Missing typedef should be generated only if at least one object of a given kind is found static --]
[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]  
    [#list SWIP.variables as variable]
      [#if variable.name=="Threads"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 9]
            [#assign threadControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if threadControlBlock != "NULL"] [#--  at least one static thread detected --]
          [#assign generateStaticTask = "yes"]
        [/#if]
      [/#if]
      
      [#if variable.name=="Queues"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign queueName = i]
          [/#if]
          [#if index == 6]
            [#assign queueControlBlock = i]
          [/#if] 
          [#assign index = index + 1]
        [/#list] 
        [#if queueName != "0"]
          [#if queueControlBlock != "NULL"]  [#--  at least one static queue detected --]
            [#assign generateStaticQueue = "yes"]
          [/#if]
        [/#if]  
      [/#if]
      
      [#if variable.name=="Timers"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign timerName = i]
          [/#if]
          [#if index == 7]
            [#assign timerControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if timerName != "0"]
          [#if timerControlBlock != "NULL"]   [#--  at least one static timer detected --]
            [#assign generateStaticTimer = "yes"]
          [/#if]          
        [/#if]  
      [/#if]
      
      [#if variable.name=="Mutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          [#if mutexControl != "NULL"]   [#--  at least one static mutex detected --]
            [#assign generateStaticMutex = "yes"]  
          [/#if]
        [/#if]
      [/#if]
     
      [#if variable.name=="RecursiveMutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          [#if mutexControl != "NULL"]   [#--  at least one static recursive mutex detected --]
            [#assign generateStaticMutex = "yes"]
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="Semaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 3]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          [#if semaphoreControl != "NULL"]   [#--  at least one static semaphore detected --]
            [#assign generateStaticSemaphore = "yes"]
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="BinarySemaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 2]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          [#if semaphoreControl != "NULL"]  [#--  at least one static binary semaphore detected --]
            [#assign generateStaticSemaphore = "yes"]
          [/#if]
        [/#if]
      [/#if]

      [#if variable.name=="Events"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign eventName = i]
          [/#if]
          [#if index == 2]
            [#assign eventControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if eventName != "0"]
          [#if eventControl != "NULL"]  [#--  at least one static binary event detected --]
            [#assign generateStaticEvent = "yes"]
          [/#if]
        [/#if]
      [/#if]
                  
    [/#list]
  [/#if]
[/#list]

[#if generateStaticTask == "yes"]
typedef StaticTask_t osStaticThreadDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticQueue == "yes"]
typedef StaticQueue_t osStaticMessageQDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticTimer == "yes"]
typedef StaticTimer_t osStaticTimerDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticMutex == "yes"]
typedef StaticSemaphore_t osStaticMutexDef_t;  [#-- missing in cmsis_os.h (v2) --]  
[/#if]
[#if generateStaticSemaphore == "yes"]
typedef StaticSemaphore_t osStaticSemaphoreDef_t;  [#-- missing in cmsis_os.h (v2) --]  
[/#if]
[#if generateStaticEvent == "yes"]
typedef StaticEventGroup_t osStaticEventGroupDef_t;  [#-- missing in cmsis_os.h (v2) --]  
[/#if]

[/#compress]
