[#ftl]
[#compress]
[#assign threadControlBlock = "NULL"]
[#assign mutexControl       = "NULL"]
[#assign timerControlBlock  = "NULL"]
[#assign queueControlBlock  = "NULL"]
[#assign semaphoreControl   = "NULL"]
[#assign generateStaticTask  = "no"]
[#assign generateStaticQueue = "no"]
[#assign generateStaticTimer = "no"]
[#assign generateStaticMutex = "no"]
[#assign generateStaticSemaphore = "no"]

[#-- Missing typedef should be generated only if at least one object of a given kind is found static --]
[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]  
    [#list SWIP.variables as variable]
      [#if variable.name=="Threads"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 9]
            [#assign threadControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if threadControlBlock != "NULL"] [#--  at least one static thread detected --]
          [#assign generateStaticTask = "yes"]
        [/#if]
      [/#if]
      
      [#if variable.name=="Queues"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign queueName = i]
          [/#if]
          [#if index == 6]
            [#assign queueControlBlock = i]
          [/#if] 
          [#assign index = index + 1]
        [/#list] 
        [#if queueName != "0"]
          [#if queueControlBlock != "NULL"]  [#--  at least one static queue detected --]
            [#assign generateStaticQueue = "yes"]
          [/#if]
        [/#if]  
      [/#if]
      
      [#if variable.name=="Timers"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign timerName = i]
          [/#if]
          [#if index == 7]
            [#assign timerControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if timerName != "0"]
          [#if timerControlBlock != "NULL"]   [#--  at least one static timer detected --]
            [#assign generateStaticTimer = "yes"]
          [/#if]          
        [/#if]  
      [/#if]
      
      [#if variable.name=="Mutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          [#if mutexControl != "NULL"]   [#--  at least one static mutex detected --]
            [#assign generateStaticMutex = "yes"]  
          [/#if]
        [/#if]
      [/#if]
     
      [#if variable.name=="RecursiveMutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          [#if mutexControl != "NULL"]   [#--  at least one static recursive mutex detected --]
            [#assign generateStaticMutex = "yes"]
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="Semaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 3]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          [#if semaphoreControl != "NULL"]   [#--  at least one static semaphore detected --]
            [#assign generateStaticSemaphore = "yes"]
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="BinarySemaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 2]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          [#if semaphoreControl != "NULL"]  [#--  at least one static binary semaphore detected --]
            [#assign generateStaticSemaphore = "yes"]
          [/#if]
        [/#if]
      [/#if]
      
    [/#list]
  [/#if]
[/#list]

[#if generateStaticTask == "yes"]
typedef StaticTask_t osStaticThreadDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticQueue == "yes"]
typedef StaticQueue_t osStaticMessageQDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticTimer == "yes"]
typedef StaticTimer_t osStaticTimerDef_t;  [#-- missing in cmsis_os.h (v2) --]
[/#if]
[#if generateStaticMutex == "yes"]
typedef StaticSemaphore_t osStaticMutexDef_t;  [#-- missing in cmsis_os.h (v2) --]  
[/#if]
[#if generateStaticSemaphore == "yes"]
typedef StaticSemaphore_t osStaticSemaphoreDef_t;  [#-- missing in cmsis_os.h (v2) --]  
[/#if]

[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]  
    [#list SWIP.variables as variable]
      [#if variable.name=="Threads"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign threadName = i]
          [/#if]
          [#if index == 1]
            [#assign threadPriority = i]
          [/#if]
          [#if index == 2]
            [#assign threadStackSize = i]
          [/#if]
          [#if index == 3]
            [#assign threadFunction = i]
          [/#if]
          [#if index == 4]
            [#assign generateFunction = i]
          [/#if]
          [#if index == 5]
            [#assign codegenOption = i]
          [/#if]
          [#if index == 6]
            [#assign threadArguments = i]
          [/#if] 
          [#if index == 7]
            [#assign threadAllocation = i]
          [/#if]
          [#if index == 8]
            [#assign threadBuffer = i]
          [/#if]
          [#if index == 9]
            [#assign threadControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        osThreadId_t ${threadName}Handle;
        [#if threadControlBlock != "NULL"]
          uint32_t ${threadBuffer}[ ${threadStackSize} ];
          osStaticThreadDef_t ${threadControlBlock};
        [/#if]
      [/#if]
      
      [#if variable.name=="Mutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 1]
            [#assign mutexAllocation = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          osMutexId_t ${mutexName}Handle;
          [#if mutexControl != "NULL"]
          osStaticMutexDef_t ${mutexControl};
          [/#if]
        [/#if]
      [/#if]
     
      [#if variable.name=="RecursiveMutexes"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign mutexName = i]
          [/#if]
          [#if index == 1]
            [#assign mutexAllocation = i]
          [/#if]
          [#if index == 2]
            [#assign mutexControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if mutexName != "0"]
          osMutexId_t ${mutexName}Handle;
          [#if mutexControl != "NULL"]
          osStaticMutexDef_t ${mutexControl};
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="Timers"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign timerName = i]
          [/#if]
          [#if index == 1]
            [#assign timerCallback = i]
          [/#if]
          [#if index == 2]
            [#assign timerType = i]
          [/#if]
          [#if index == 3]
            [#assign generateCallback = i]
          [/#if]
          [#if index == 4]
            [#assign timerCodeGen = i]
          [/#if]
          [#if index == 5]
            [#assign timerParameters = i]
          [/#if]
          [#if index == 6]
            [#assign timerAllocation = i]
          [/#if]
          [#if index == 7]
            [#assign timerControlBlock = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if timerName != "0"]
          osTimerId_t ${timerName}Handle;
          [#if timerControlBlock != "NULL"]
          osStaticTimerDef_t ${timerControlBlock};
          [/#if]          
        [/#if]  
      [/#if]
      
      [#if variable.name=="Queues"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign queueName = i]
          [/#if]
          [#if index == 1]
            [#assign queueSize = i]
          [/#if]
          [#if index == 2]
            [#assign queueElementType = i]
          [/#if]
          [#if index == 3]
            [#assign queueIsIntegerType = i]
          [/#if]
          [#if index == 4]
            [#assign queueAllocation = i]
          [/#if]
          [#if index == 5]
            [#assign queueBuffer = i]
          [/#if]
          [#if index == 6]
            [#assign queueControlBlock = i]
          [/#if] 
          [#assign index = index + 1]
        [/#list] 
        [#if queueName != "0"]
           osMessageQueueId_t ${queueName}Handle;
          [#if queueControlBlock != "NULL"]
           [#if queueIsIntegerType = "0"]
           uint8_t ${queueBuffer}[ ${queueSize} * sizeof( ${queueElementType} ) ];
           [#else]
           uint8_t ${queueBuffer}[ ${queueSize} * ${queueElementType} ];
           [/#if]
           osStaticMessageQDef_t ${queueControlBlock};
          [/#if]
        [/#if]  
      [/#if]
    
      [#if variable.name=="Semaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 2]
            [#assign semaphoreAllocation = i]
          [/#if]
          [#if index == 3]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          osSemaphoreId_t ${semaphoreName}Handle;
          [#if semaphoreControl != "NULL"]
          osStaticSemaphoreDef_t ${semaphoreControl};
          [/#if]
        [/#if]
      [/#if]
      
      [#if variable.name=="BinarySemaphores"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as i]
          [#if index == 0]
            [#assign semaphoreName = i]
          [/#if]
          [#if index == 1]
            [#assign semaphoreAllocation = i]
          [/#if]
          [#if index == 2]
            [#assign semaphoreControl = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [#if semaphoreName != "0"]
          osSemaphoreId_t ${semaphoreName}Handle;
          [#if semaphoreControl != "NULL"]
          osStaticSemaphoreDef_t ${semaphoreControl};
          [/#if]
        [/#if]
      [/#if]
      
    [/#list] 
     
  [/#if]
[/#list]
[/#compress]
