[#ftl]
[#compress]
[#assign nbThreads = 0]
[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]
	[#list SWIP.variables as variable]
	
	  [#if variable.name == "Threads"]
	    [#assign s = variable.valueList]
	    [#assign index = 0]
        [#list s as i]
          [#if index == 3]
            [#assign threadFunction = i]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        void ${threadFunction}(void const * argument);
      [/#if]
      
 	  [#if variable.name == "Timers"]
	    [#assign s = variable.valueList]
	    [#assign index = 0]
        [#list s as i]
          [#if index == 1]
            [#assign timerCallback = i]
          [/#if]
          [#if index == 3]
            [#assign generateCallback = i]
          [/#if] 
          [#assign index = index + 1]
        [/#list]
        [#if generateCallback == "1"]
        void ${timerCallback}(void const * argument);
        [/#if]
      [/#if]     
      
	[/#list]
  [/#if]
[/#list]
[/#compress]
