[#ftl]
[#compress]
[#assign CMSIS_version = "unknown"]
[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]
	[#list SWIP.variables as variable]
	  [#if variable.name=="CMSIS_version"]
        [#assign CMSIS_version = variable.value]
	  [/#if]
    [/#list]
  [/#if]
[/#list]
[#if CMSIS_version == "2.00"]  [#--Nothing was generated in CMSI-RTOS v1 --]
#t/* Init scheduler */
#tosKernelInitialize();
[/#if]
[/#compress]
