[#ftl]
[#list IPdatas as IP]  
    [#-- Global variables --]
    [#if IP.variablesForMw??]
        [#list IP.variablesForMw as variable]
            [#assign ipname= IP.ipName]
            [#if variable.name?contains(ipname)]
${variable.value} ${variable.name};
            [/#if]       
        [/#list]
    [/#if]
    [#list IP.configModelList as instanceData]
        [#assign IPUsedWithBSP = "false"] 
        [#if instanceData.isBSPUsed=="true"]
            [#assign IPUsedWithBSP = "true"] 
        [#else]
            [#assign IPUsedWithBSP = "false"]
        [/#if]
    [/#list]
[/#list]
[#if (ipname?? && !((ipname?contains("USB_OTG")) && (FamilyName=="STM32H7RS"))) || !ipname??]
void Error_Handler(void);
[/#if]

[#if IPUsedWithBSP?? && IPUsedWithBSP == "true"]
    [#if IPhandlers??]
        [#list IPhandlers as handler]
${handler.getHandlerType()} ${handler.getHandler()};
        [/#list]
    [/#if]
[/#if]