[#ftl]
/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    ${name}
  * @author  MCD Application Team
  * @brief   Header for custom_stm.c module.
  ******************************************************************************
[@common.optinclude name=mxTmpFolder+"/license.tmp"/][#--include License text --]
  ******************************************************************************
  */
/* USER CODE END Header */

[#assign NUMBER_OF_SERVICES = "0"]

[#assign SERVICE1_NUMBER_OF_CHARACTERISTICS = 0]
[#assign SERVICE2_NUMBER_OF_CHARACTERISTICS = 0]
[#assign SERVICE3_NUMBER_OF_CHARACTERISTICS = 0]
[#assign SERVICE4_NUMBER_OF_CHARACTERISTICS = 0]
[#assign SERVICE5_NUMBER_OF_CHARACTERISTICS = 0]

[#assign SERVICE1_LONG_NAME = ""]
[#assign SERVICE2_LONG_NAME = ""]
[#assign SERVICE3_LONG_NAME = ""]
[#assign SERVICE4_LONG_NAME = ""]
[#assign SERVICE5_LONG_NAME = ""]

[#assign SERVICE1_SHORT_NAME = ""]
[#assign SERVICE2_SHORT_NAME = ""]
[#assign SERVICE3_SHORT_NAME = ""]
[#assign SERVICE4_SHORT_NAME = ""]
[#assign SERVICE5_SHORT_NAME = ""]

[#assign SERVICE1_CHAR1_LONG_NAME = ""]
[#assign SERVICE1_CHAR2_LONG_NAME = ""]
[#assign SERVICE1_CHAR3_LONG_NAME = ""]
[#assign SERVICE1_CHAR4_LONG_NAME = ""]
[#assign SERVICE1_CHAR5_LONG_NAME = ""]
[#assign SERVICE2_CHAR1_LONG_NAME = ""]
[#assign SERVICE2_CHAR2_LONG_NAME = ""]
[#assign SERVICE2_CHAR3_LONG_NAME = ""]
[#assign SERVICE2_CHAR4_LONG_NAME = ""]
[#assign SERVICE2_CHAR5_LONG_NAME = ""]
[#assign SERVICE3_CHAR1_LONG_NAME = ""]
[#assign SERVICE3_CHAR2_LONG_NAME = ""]
[#assign SERVICE3_CHAR3_LONG_NAME = ""]
[#assign SERVICE3_CHAR4_LONG_NAME = ""]
[#assign SERVICE3_CHAR5_LONG_NAME = ""]
[#assign SERVICE4_CHAR1_LONG_NAME = ""]
[#assign SERVICE4_CHAR2_LONG_NAME = ""]
[#assign SERVICE4_CHAR3_LONG_NAME = ""]
[#assign SERVICE4_CHAR4_LONG_NAME = ""]
[#assign SERVICE4_CHAR5_LONG_NAME = ""]
[#assign SERVICE5_CHAR1_LONG_NAME = ""]
[#assign SERVICE5_CHAR2_LONG_NAME = ""]
[#assign SERVICE5_CHAR3_LONG_NAME = ""]
[#assign SERVICE5_CHAR4_LONG_NAME = ""]
[#assign SERVICE5_CHAR5_LONG_NAME = ""]

[#assign SERVICE1_CHAR1_SHORT_NAME = ""]
[#assign SERVICE1_CHAR2_SHORT_NAME = ""]
[#assign SERVICE1_CHAR3_SHORT_NAME = ""]
[#assign SERVICE1_CHAR4_SHORT_NAME = ""]
[#assign SERVICE1_CHAR5_SHORT_NAME = ""]
[#assign SERVICE2_CHAR1_SHORT_NAME = ""]
[#assign SERVICE2_CHAR2_SHORT_NAME = ""]
[#assign SERVICE2_CHAR3_SHORT_NAME = ""]
[#assign SERVICE2_CHAR4_SHORT_NAME = ""]
[#assign SERVICE2_CHAR5_SHORT_NAME = ""]
[#assign SERVICE3_CHAR1_SHORT_NAME = ""]
[#assign SERVICE3_CHAR2_SHORT_NAME = ""]
[#assign SERVICE3_CHAR3_SHORT_NAME = ""]
[#assign SERVICE3_CHAR4_SHORT_NAME = ""]
[#assign SERVICE3_CHAR5_SHORT_NAME = ""]
[#assign SERVICE4_CHAR1_SHORT_NAME = ""]
[#assign SERVICE4_CHAR2_SHORT_NAME = ""]
[#assign SERVICE4_CHAR3_SHORT_NAME = ""]
[#assign SERVICE4_CHAR4_SHORT_NAME = ""]
[#assign SERVICE4_CHAR5_SHORT_NAME = ""]
[#assign SERVICE5_CHAR1_SHORT_NAME = ""]
[#assign SERVICE5_CHAR2_SHORT_NAME = ""]
[#assign SERVICE5_CHAR3_SHORT_NAME = ""]
[#assign SERVICE5_CHAR4_SHORT_NAME = ""]
[#assign SERVICE5_CHAR5_SHORT_NAME = ""]

[#assign SERVICE1_CHAR1_PROP_BROADCAST = ""]
[#assign SERVICE1_CHAR2_PROP_BROADCAST = ""]
[#assign SERVICE1_CHAR3_PROP_BROADCAST = ""]
[#assign SERVICE1_CHAR4_PROP_BROADCAST = ""]
[#assign SERVICE1_CHAR5_PROP_BROADCAST = ""]
[#assign SERVICE2_CHAR1_PROP_BROADCAST = ""]
[#assign SERVICE2_CHAR2_PROP_BROADCAST = ""]
[#assign SERVICE2_CHAR3_PROP_BROADCAST = ""]
[#assign SERVICE2_CHAR4_PROP_BROADCAST = ""]
[#assign SERVICE2_CHAR5_PROP_BROADCAST = ""]
[#assign SERVICE3_CHAR1_PROP_BROADCAST = ""]
[#assign SERVICE3_CHAR2_PROP_BROADCAST = ""]
[#assign SERVICE3_CHAR3_PROP_BROADCAST = ""]
[#assign SERVICE3_CHAR4_PROP_BROADCAST = ""]
[#assign SERVICE3_CHAR5_PROP_BROADCAST = ""]
[#assign SERVICE4_CHAR1_PROP_BROADCAST = ""]
[#assign SERVICE4_CHAR2_PROP_BROADCAST = ""]
[#assign SERVICE4_CHAR3_PROP_BROADCAST = ""]
[#assign SERVICE4_CHAR4_PROP_BROADCAST = ""]
[#assign SERVICE4_CHAR5_PROP_BROADCAST = ""]
[#assign SERVICE5_CHAR1_PROP_BROADCAST = ""]
[#assign SERVICE5_CHAR2_PROP_BROADCAST = ""]
[#assign SERVICE5_CHAR3_PROP_BROADCAST = ""]
[#assign SERVICE5_CHAR4_PROP_BROADCAST = ""]
[#assign SERVICE5_CHAR5_PROP_BROADCAST = ""]

[#assign SERVICE1_CHAR1_PROP_READ = ""]
[#assign SERVICE1_CHAR2_PROP_READ = ""]
[#assign SERVICE1_CHAR3_PROP_READ = ""]
[#assign SERVICE1_CHAR4_PROP_READ = ""]
[#assign SERVICE1_CHAR5_PROP_READ = ""]
[#assign SERVICE2_CHAR1_PROP_READ = ""]
[#assign SERVICE2_CHAR2_PROP_READ = ""]
[#assign SERVICE2_CHAR3_PROP_READ = ""]
[#assign SERVICE2_CHAR4_PROP_READ = ""]
[#assign SERVICE2_CHAR5_PROP_READ = ""]
[#assign SERVICE3_CHAR1_PROP_READ = ""]
[#assign SERVICE3_CHAR2_PROP_READ = ""]
[#assign SERVICE3_CHAR3_PROP_READ = ""]
[#assign SERVICE3_CHAR4_PROP_READ = ""]
[#assign SERVICE3_CHAR5_PROP_READ = ""]
[#assign SERVICE4_CHAR1_PROP_READ = ""]
[#assign SERVICE4_CHAR2_PROP_READ = ""]
[#assign SERVICE4_CHAR3_PROP_READ = ""]
[#assign SERVICE4_CHAR4_PROP_READ = ""]
[#assign SERVICE4_CHAR5_PROP_READ = ""]
[#assign SERVICE5_CHAR1_PROP_READ = ""]
[#assign SERVICE5_CHAR2_PROP_READ = ""]
[#assign SERVICE5_CHAR3_PROP_READ = ""]
[#assign SERVICE5_CHAR4_PROP_READ = ""]
[#assign SERVICE5_CHAR5_PROP_READ = ""]

[#assign SERVICE1_CHAR1_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE1_CHAR2_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE1_CHAR3_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE1_CHAR4_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE1_CHAR5_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE2_CHAR1_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE2_CHAR2_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE2_CHAR3_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE2_CHAR4_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE2_CHAR5_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE3_CHAR1_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE3_CHAR2_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE3_CHAR3_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE3_CHAR4_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE3_CHAR5_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE4_CHAR1_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE4_CHAR2_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE4_CHAR3_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE4_CHAR4_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE4_CHAR5_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE5_CHAR1_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE5_CHAR2_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE5_CHAR3_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE5_CHAR4_PROP_WRITE_WITHOUT_RESP = ""]
[#assign SERVICE5_CHAR5_PROP_WRITE_WITHOUT_RESP = ""]

[#assign SERVICE1_CHAR1_PROP_WRITE = ""]
[#assign SERVICE1_CHAR2_PROP_WRITE = ""]
[#assign SERVICE1_CHAR3_PROP_WRITE = ""]
[#assign SERVICE1_CHAR4_PROP_WRITE = ""]
[#assign SERVICE1_CHAR5_PROP_WRITE = ""]
[#assign SERVICE2_CHAR1_PROP_WRITE = ""]
[#assign SERVICE2_CHAR2_PROP_WRITE = ""]
[#assign SERVICE2_CHAR3_PROP_WRITE = ""]
[#assign SERVICE2_CHAR4_PROP_WRITE = ""]
[#assign SERVICE2_CHAR5_PROP_WRITE = ""]
[#assign SERVICE3_CHAR1_PROP_WRITE = ""]
[#assign SERVICE3_CHAR2_PROP_WRITE = ""]
[#assign SERVICE3_CHAR3_PROP_WRITE = ""]
[#assign SERVICE3_CHAR4_PROP_WRITE = ""]
[#assign SERVICE3_CHAR5_PROP_WRITE = ""]
[#assign SERVICE4_CHAR1_PROP_WRITE = ""]
[#assign SERVICE4_CHAR2_PROP_WRITE = ""]
[#assign SERVICE4_CHAR3_PROP_WRITE = ""]
[#assign SERVICE4_CHAR4_PROP_WRITE = ""]
[#assign SERVICE4_CHAR5_PROP_WRITE = ""]
[#assign SERVICE5_CHAR1_PROP_WRITE = ""]
[#assign SERVICE5_CHAR2_PROP_WRITE = ""]
[#assign SERVICE5_CHAR3_PROP_WRITE = ""]
[#assign SERVICE5_CHAR4_PROP_WRITE = ""]
[#assign SERVICE5_CHAR5_PROP_WRITE = ""]

[#assign SERVICE1_CHAR1_PROP_NOTIFY = ""]
[#assign SERVICE1_CHAR2_PROP_NOTIFY = ""]
[#assign SERVICE1_CHAR3_PROP_NOTIFY = ""]
[#assign SERVICE1_CHAR4_PROP_NOTIFY = ""]
[#assign SERVICE1_CHAR5_PROP_NOTIFY = ""]
[#assign SERVICE2_CHAR1_PROP_NOTIFY = ""]
[#assign SERVICE2_CHAR2_PROP_NOTIFY = ""]
[#assign SERVICE2_CHAR3_PROP_NOTIFY = ""]
[#assign SERVICE2_CHAR4_PROP_NOTIFY = ""]
[#assign SERVICE2_CHAR5_PROP_NOTIFY = ""]
[#assign SERVICE3_CHAR1_PROP_NOTIFY = ""]
[#assign SERVICE3_CHAR2_PROP_NOTIFY = ""]
[#assign SERVICE3_CHAR3_PROP_NOTIFY = ""]
[#assign SERVICE3_CHAR4_PROP_NOTIFY = ""]
[#assign SERVICE3_CHAR5_PROP_NOTIFY = ""]
[#assign SERVICE4_CHAR1_PROP_NOTIFY = ""]
[#assign SERVICE4_CHAR2_PROP_NOTIFY = ""]
[#assign SERVICE4_CHAR3_PROP_NOTIFY = ""]
[#assign SERVICE4_CHAR4_PROP_NOTIFY = ""]
[#assign SERVICE4_CHAR5_PROP_NOTIFY = ""]
[#assign SERVICE5_CHAR1_PROP_NOTIFY = ""]
[#assign SERVICE5_CHAR2_PROP_NOTIFY = ""]
[#assign SERVICE5_CHAR3_PROP_NOTIFY = ""]
[#assign SERVICE5_CHAR4_PROP_NOTIFY = ""]
[#assign SERVICE5_CHAR5_PROP_NOTIFY = ""]

[#assign SERVICE1_CHAR1_PROP_INDICATE = ""]
[#assign SERVICE1_CHAR2_PROP_INDICATE = ""]
[#assign SERVICE1_CHAR3_PROP_INDICATE = ""]
[#assign SERVICE1_CHAR4_PROP_INDICATE = ""]
[#assign SERVICE1_CHAR5_PROP_INDICATE = ""]
[#assign SERVICE2_CHAR1_PROP_INDICATE = ""]
[#assign SERVICE2_CHAR2_PROP_INDICATE = ""]
[#assign SERVICE2_CHAR3_PROP_INDICATE = ""]
[#assign SERVICE2_CHAR4_PROP_INDICATE = ""]
[#assign SERVICE2_CHAR5_PROP_INDICATE = ""]
[#assign SERVICE3_CHAR1_PROP_INDICATE = ""]
[#assign SERVICE3_CHAR2_PROP_INDICATE = ""]
[#assign SERVICE3_CHAR3_PROP_INDICATE = ""]
[#assign SERVICE3_CHAR4_PROP_INDICATE = ""]
[#assign SERVICE3_CHAR5_PROP_INDICATE = ""]
[#assign SERVICE4_CHAR1_PROP_INDICATE = ""]
[#assign SERVICE4_CHAR2_PROP_INDICATE = ""]
[#assign SERVICE4_CHAR3_PROP_INDICATE = ""]
[#assign SERVICE4_CHAR4_PROP_INDICATE = ""]
[#assign SERVICE4_CHAR5_PROP_INDICATE = ""]
[#assign SERVICE5_CHAR1_PROP_INDICATE = ""]
[#assign SERVICE5_CHAR2_PROP_INDICATE = ""]
[#assign SERVICE5_CHAR3_PROP_INDICATE = ""]
[#assign SERVICE5_CHAR4_PROP_INDICATE = ""]
[#assign SERVICE5_CHAR5_PROP_INDICATE = ""]

[#assign SERVICE1_CHAR1_VALUE_LENGTH = 0]
[#assign SERVICE1_CHAR2_VALUE_LENGTH = 0]
[#assign SERVICE1_CHAR3_VALUE_LENGTH = 0]
[#assign SERVICE1_CHAR4_VALUE_LENGTH = 0]
[#assign SERVICE1_CHAR5_VALUE_LENGTH = 0]
[#assign SERVICE2_CHAR1_VALUE_LENGTH = 0]
[#assign SERVICE2_CHAR2_VALUE_LENGTH = 0]
[#assign SERVICE2_CHAR3_VALUE_LENGTH = 0]
[#assign SERVICE2_CHAR4_VALUE_LENGTH = 0]
[#assign SERVICE2_CHAR5_VALUE_LENGTH = 0]
[#assign SERVICE3_CHAR1_VALUE_LENGTH = 0]
[#assign SERVICE3_CHAR2_VALUE_LENGTH = 0]
[#assign SERVICE3_CHAR3_VALUE_LENGTH = 0]
[#assign SERVICE3_CHAR4_VALUE_LENGTH = 0]
[#assign SERVICE3_CHAR5_VALUE_LENGTH = 0]
[#assign SERVICE4_CHAR1_VALUE_LENGTH = 0]
[#assign SERVICE4_CHAR2_VALUE_LENGTH = 0]
[#assign SERVICE4_CHAR3_VALUE_LENGTH = 0]
[#assign SERVICE4_CHAR4_VALUE_LENGTH = 0]
[#assign SERVICE4_CHAR5_VALUE_LENGTH = 0]
[#assign SERVICE5_CHAR1_VALUE_LENGTH = 0]
[#assign SERVICE5_CHAR2_VALUE_LENGTH = 0]
[#assign SERVICE5_CHAR3_VALUE_LENGTH = 0]
[#assign SERVICE5_CHAR4_VALUE_LENGTH = 0]
[#assign SERVICE5_CHAR5_VALUE_LENGTH = 0]

[#list SWIPdatas as SWIP]
    [#if SWIP.defines??]
        [#list SWIP.defines as definition]
            [#if (definition.name == "NUMBER_OF_SERVICES")]
                [#assign NUMBER_OF_SERVICES = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_NUMBER_OF_CHARACTERISTICS")]
                [#assign SERVICE1_NUMBER_OF_CHARACTERISTICS = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_NUMBER_OF_CHARACTERISTICS")]
                [#assign SERVICE2_NUMBER_OF_CHARACTERISTICS = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_NUMBER_OF_CHARACTERISTICS")]
                [#assign SERVICE3_NUMBER_OF_CHARACTERISTICS = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_NUMBER_OF_CHARACTERISTICS")]
                [#assign SERVICE4_NUMBER_OF_CHARACTERISTICS = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_NUMBER_OF_CHARACTERISTICS")]
                [#assign SERVICE5_NUMBER_OF_CHARACTERISTICS = definition.value]
            [/#if]

            [#if (definition.name == "SERVICE1_LONG_NAME")]
                [#assign SERVICE1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_LONG_NAME")]
                [#assign SERVICE2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_LONG_NAME")]
                [#assign SERVICE3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_LONG_NAME")]
                [#assign SERVICE4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_LONG_NAME")]
                [#assign SERVICE5_LONG_NAME = definition.value]
            [/#if]

            [#if (definition.name == "SERVICE1_SHORT_NAME")]
                [#assign SERVICE1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_SHORT_NAME")]
                [#assign SERVICE2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_SHORT_NAME")]
                [#assign SERVICE3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_SHORT_NAME")]
                [#assign SERVICE4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_SHORT_NAME")]
                [#assign SERVICE5_SHORT_NAME = definition.value]
            [/#if]

            [#if (definition.name == "SERVICE1_CHAR1_LONG_NAME")]
                [#assign SERVICE1_CHAR1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR2_LONG_NAME")]
                [#assign SERVICE1_CHAR2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR3_LONG_NAME")]
                [#assign SERVICE1_CHAR3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR4_LONG_NAME")]
                [#assign SERVICE1_CHAR4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR5_LONG_NAME")]
                [#assign SERVICE1_CHAR5_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR1_LONG_NAME")]
                [#assign SERVICE2_CHAR1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR2_LONG_NAME")]
                [#assign SERVICE2_CHAR2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR3_LONG_NAME")]
                [#assign SERVICE2_CHAR3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR4_LONG_NAME")]
                [#assign SERVICE2_CHAR4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR5_LONG_NAME")]
                [#assign SERVICE2_CHAR5_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR1_LONG_NAME")]
                [#assign SERVICE3_CHAR1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR2_LONG_NAME")]
                [#assign SERVICE3_CHAR2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR3_LONG_NAME")]
                [#assign SERVICE3_CHAR3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR4_LONG_NAME")]
                [#assign SERVICE3_CHAR4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR5_LONG_NAME")]
                [#assign SERVICE3_CHAR5_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR1_LONG_NAME")]
                [#assign SERVICE4_CHAR1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR2_LONG_NAME")]
                [#assign SERVICE4_CHAR2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR3_LONG_NAME")]
                [#assign SERVICE4_CHAR3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR4_LONG_NAME")]
                [#assign SERVICE4_CHAR4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR5_LONG_NAME")]
                [#assign SERVICE4_CHAR5_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR1_LONG_NAME")]
                [#assign SERVICE5_CHAR1_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR2_LONG_NAME")]
                [#assign SERVICE5_CHAR2_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR3_LONG_NAME")]
                [#assign SERVICE5_CHAR3_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR4_LONG_NAME")]
                [#assign SERVICE5_CHAR4_LONG_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR5_LONG_NAME")]
                [#assign SERVICE5_CHAR5_LONG_NAME = definition.value]
            [/#if]

            [#if (definition.name == "SERVICE1_CHAR1_SHORT_NAME")]
                [#assign SERVICE1_CHAR1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR2_SHORT_NAME")]
                [#assign SERVICE1_CHAR2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR3_SHORT_NAME")]
                [#assign SERVICE1_CHAR3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR4_SHORT_NAME")]
                [#assign SERVICE1_CHAR4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR5_SHORT_NAME")]
                [#assign SERVICE1_CHAR5_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR1_SHORT_NAME")]
                [#assign SERVICE2_CHAR1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR2_SHORT_NAME")]
                [#assign SERVICE2_CHAR2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR3_SHORT_NAME")]
                [#assign SERVICE2_CHAR3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR4_SHORT_NAME")]
                [#assign SERVICE2_CHAR4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR5_SHORT_NAME")]
                [#assign SERVICE2_CHAR5_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR1_SHORT_NAME")]
                [#assign SERVICE3_CHAR1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR2_SHORT_NAME")]
                [#assign SERVICE3_CHAR2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR3_SHORT_NAME")]
                [#assign SERVICE3_CHAR3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR4_SHORT_NAME")]
                [#assign SERVICE3_CHAR4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR5_SHORT_NAME")]
                [#assign SERVICE3_CHAR5_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR1_SHORT_NAME")]
                [#assign SERVICE4_CHAR1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR2_SHORT_NAME")]
                [#assign SERVICE4_CHAR2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR3_SHORT_NAME")]
                [#assign SERVICE4_CHAR3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR4_SHORT_NAME")]
                [#assign SERVICE4_CHAR4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR5_SHORT_NAME")]
                [#assign SERVICE4_CHAR5_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR1_SHORT_NAME")]
                [#assign SERVICE5_CHAR1_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR2_SHORT_NAME")]
                [#assign SERVICE5_CHAR2_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR3_SHORT_NAME")]
                [#assign SERVICE5_CHAR3_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR4_SHORT_NAME")]
                [#assign SERVICE5_CHAR4_SHORT_NAME = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR5_SHORT_NAME")]
                [#assign SERVICE5_CHAR5_SHORT_NAME = definition.value]
            [/#if]

            [#if (definition.name == "SERVICE1_CHAR1_VALUE_LENGTH")]
                [#assign SERVICE1_CHAR1_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR2_VALUE_LENGTH")]
                [#assign SERVICE1_CHAR2_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR3_VALUE_LENGTH")]
                [#assign SERVICE1_CHAR3_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR4_VALUE_LENGTH")]
                [#assign SERVICE1_CHAR4_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE1_CHAR5_VALUE_LENGTH")]
                [#assign SERVICE1_CHAR5_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR1_VALUE_LENGTH")]
                [#assign SERVICE2_CHAR1_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR2_VALUE_LENGTH")]
                [#assign SERVICE2_CHAR2_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR3_VALUE_LENGTH")]
                [#assign SERVICE2_CHAR3_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR4_VALUE_LENGTH")]
                [#assign SERVICE2_CHAR4_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE2_CHAR5_VALUE_LENGTH")]
                [#assign SERVICE2_CHAR5_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR1_VALUE_LENGTH")]
                [#assign SERVICE3_CHAR1_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR2_VALUE_LENGTH")]
                [#assign SERVICE3_CHAR2_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR3_VALUE_LENGTH")]
                [#assign SERVICE3_CHAR3_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR4_VALUE_LENGTH")]
                [#assign SERVICE3_CHAR4_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE3_CHAR5_VALUE_LENGTH")]
                [#assign SERVICE3_CHAR5_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR1_VALUE_LENGTH")]
                [#assign SERVICE4_CHAR1_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR2_VALUE_LENGTH")]
                [#assign SERVICE4_CHAR2_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR3_VALUE_LENGTH")]
                [#assign SERVICE4_CHAR3_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR4_VALUE_LENGTH")]
                [#assign SERVICE4_CHAR4_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE4_CHAR5_VALUE_LENGTH")]
                [#assign SERVICE4_CHAR5_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR1_VALUE_LENGTH")]
                [#assign SERVICE5_CHAR1_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR2_VALUE_LENGTH")]
                [#assign SERVICE5_CHAR2_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR3_VALUE_LENGTH")]
                [#assign SERVICE5_CHAR3_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR4_VALUE_LENGTH")]
                [#assign SERVICE5_CHAR4_VALUE_LENGTH = definition.value]
            [/#if]
            [#if (definition.name == "SERVICE5_CHAR5_VALUE_LENGTH")]
                [#assign SERVICE5_CHAR5_VALUE_LENGTH = definition.value]
            [/#if]


            [#if definition.value != ""]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_BROADCAST")]
                    [#assign SERVICE1_CHAR1_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_BROADCAST")]
                    [#assign SERVICE1_CHAR2_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_BROADCAST")]
                    [#assign SERVICE1_CHAR3_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_BROADCAST")]
                    [#assign SERVICE1_CHAR4_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_BROADCAST")]
                    [#assign SERVICE1_CHAR5_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_BROADCAST")]
                    [#assign SERVICE2_CHAR1_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_BROADCAST")]
                    [#assign SERVICE2_CHAR2_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_BROADCAST")]
                    [#assign SERVICE2_CHAR3_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_BROADCAST")]
                    [#assign SERVICE2_CHAR4_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_BROADCAST")]
                    [#assign SERVICE2_CHAR5_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_BROADCAST")]
                    [#assign SERVICE3_CHAR1_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_BROADCAST")]
                    [#assign SERVICE3_CHAR2_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_BROADCAST")]
                    [#assign SERVICE3_CHAR3_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_BROADCAST")]
                    [#assign SERVICE3_CHAR4_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_BROADCAST")]
                    [#assign SERVICE3_CHAR5_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_BROADCAST")]
                    [#assign SERVICE4_CHAR1_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_BROADCAST")]
                    [#assign SERVICE4_CHAR2_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_BROADCAST")]
                    [#assign SERVICE4_CHAR3_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_BROADCAST")]
                    [#assign SERVICE4_CHAR4_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_BROADCAST")]
                    [#assign SERVICE4_CHAR5_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_BROADCAST")]
                    [#assign SERVICE5_CHAR1_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_BROADCAST")]
                    [#assign SERVICE5_CHAR2_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_BROADCAST")]
                    [#assign SERVICE5_CHAR3_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_BROADCAST")]
                    [#assign SERVICE5_CHAR4_PROP_BROADCAST = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_BROADCAST")]
                    [#assign SERVICE5_CHAR5_PROP_BROADCAST = definition.value]
                [/#if]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_READ")]
                    [#assign SERVICE1_CHAR1_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_READ")]
                    [#assign SERVICE1_CHAR2_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_READ")]
                    [#assign SERVICE1_CHAR3_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_READ")]
                    [#assign SERVICE1_CHAR4_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_READ")]
                    [#assign SERVICE1_CHAR5_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_READ")]
                    [#assign SERVICE2_CHAR1_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_READ")]
                    [#assign SERVICE2_CHAR2_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_READ")]
                    [#assign SERVICE2_CHAR3_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_READ")]
                    [#assign SERVICE2_CHAR4_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_READ")]
                    [#assign SERVICE2_CHAR5_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_READ")]
                    [#assign SERVICE3_CHAR1_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_READ")]
                    [#assign SERVICE3_CHAR2_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_READ")]
                    [#assign SERVICE3_CHAR3_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_READ")]
                    [#assign SERVICE3_CHAR4_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_READ")]
                    [#assign SERVICE3_CHAR5_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_READ")]
                    [#assign SERVICE4_CHAR1_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_READ")]
                    [#assign SERVICE4_CHAR2_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_READ")]
                    [#assign SERVICE4_CHAR3_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_READ")]
                    [#assign SERVICE4_CHAR4_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_READ")]
                    [#assign SERVICE4_CHAR5_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_READ")]
                    [#assign SERVICE5_CHAR1_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_READ")]
                    [#assign SERVICE5_CHAR2_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_READ")]
                    [#assign SERVICE5_CHAR3_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_READ")]
                    [#assign SERVICE5_CHAR4_PROP_READ = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_READ")]
                    [#assign SERVICE5_CHAR5_PROP_READ = definition.value]
                [/#if]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE1_CHAR1_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE1_CHAR2_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE1_CHAR3_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE1_CHAR4_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE1_CHAR5_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE2_CHAR1_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE2_CHAR2_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE2_CHAR3_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE2_CHAR4_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE2_CHAR5_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE3_CHAR1_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE3_CHAR2_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE3_CHAR3_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE3_CHAR4_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE3_CHAR5_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE4_CHAR1_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE4_CHAR2_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE4_CHAR3_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE4_CHAR4_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE4_CHAR5_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE5_CHAR1_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE5_CHAR2_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE5_CHAR3_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE5_CHAR4_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_WRITE_WITHOUT_RESP")]
                    [#assign SERVICE5_CHAR5_PROP_WRITE_WITHOUT_RESP = definition.value]
                [/#if]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_WRITE")]
                    [#assign SERVICE1_CHAR1_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_WRITE")]
                    [#assign SERVICE1_CHAR2_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_WRITE")]
                    [#assign SERVICE1_CHAR3_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_WRITE")]
                    [#assign SERVICE1_CHAR4_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_WRITE")]
                    [#assign SERVICE1_CHAR5_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_WRITE")]
                    [#assign SERVICE2_CHAR1_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_WRITE")]
                    [#assign SERVICE2_CHAR2_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_WRITE")]
                    [#assign SERVICE2_CHAR3_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_WRITE")]
                    [#assign SERVICE2_CHAR4_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_WRITE")]
                    [#assign SERVICE2_CHAR5_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_WRITE")]
                    [#assign SERVICE3_CHAR1_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_WRITE")]
                    [#assign SERVICE3_CHAR2_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_WRITE")]
                    [#assign SERVICE3_CHAR3_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_WRITE")]
                    [#assign SERVICE3_CHAR4_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_WRITE")]
                    [#assign SERVICE3_CHAR5_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_WRITE")]
                    [#assign SERVICE4_CHAR1_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_WRITE")]
                    [#assign SERVICE4_CHAR2_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_WRITE")]
                    [#assign SERVICE4_CHAR3_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_WRITE")]
                    [#assign SERVICE4_CHAR4_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_WRITE")]
                    [#assign SERVICE4_CHAR5_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_WRITE")]
                    [#assign SERVICE5_CHAR1_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_WRITE")]
                    [#assign SERVICE5_CHAR2_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_WRITE")]
                    [#assign SERVICE5_CHAR3_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_WRITE")]
                    [#assign SERVICE5_CHAR4_PROP_WRITE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_WRITE")]
                    [#assign SERVICE5_CHAR5_PROP_WRITE = definition.value]
                [/#if]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_NOTIFY")]
                    [#assign SERVICE1_CHAR1_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_NOTIFY")]
                    [#assign SERVICE1_CHAR2_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_NOTIFY")]
                    [#assign SERVICE1_CHAR3_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_NOTIFY")]
                    [#assign SERVICE1_CHAR4_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_NOTIFY")]
                    [#assign SERVICE1_CHAR5_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_NOTIFY")]
                    [#assign SERVICE2_CHAR1_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_NOTIFY")]
                    [#assign SERVICE2_CHAR2_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_NOTIFY")]
                    [#assign SERVICE2_CHAR3_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_NOTIFY")]
                    [#assign SERVICE2_CHAR4_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_NOTIFY")]
                    [#assign SERVICE2_CHAR5_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_NOTIFY")]
                    [#assign SERVICE3_CHAR1_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_NOTIFY")]
                    [#assign SERVICE3_CHAR2_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_NOTIFY")]
                    [#assign SERVICE3_CHAR3_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_NOTIFY")]
                    [#assign SERVICE3_CHAR4_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_NOTIFY")]
                    [#assign SERVICE3_CHAR5_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_NOTIFY")]
                    [#assign SERVICE4_CHAR1_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_NOTIFY")]
                    [#assign SERVICE4_CHAR2_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_NOTIFY")]
                    [#assign SERVICE4_CHAR3_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_NOTIFY")]
                    [#assign SERVICE4_CHAR4_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_NOTIFY")]
                    [#assign SERVICE4_CHAR5_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_NOTIFY")]
                    [#assign SERVICE5_CHAR1_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_NOTIFY")]
                    [#assign SERVICE5_CHAR2_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_NOTIFY")]
                    [#assign SERVICE5_CHAR3_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_NOTIFY")]
                    [#assign SERVICE5_CHAR4_PROP_NOTIFY = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_NOTIFY")]
                    [#assign SERVICE5_CHAR5_PROP_NOTIFY = definition.value]
                [/#if]

                [#if (definition.name == "SERVICE1_CHAR1_PROP_INDICATE")]
                    [#assign SERVICE1_CHAR1_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR2_PROP_INDICATE")]
                    [#assign SERVICE1_CHAR2_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR3_PROP_INDICATE")]
                    [#assign SERVICE1_CHAR3_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR4_PROP_INDICATE")]
                    [#assign SERVICE1_CHAR4_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE1_CHAR5_PROP_INDICATE")]
                    [#assign SERVICE1_CHAR5_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR1_PROP_INDICATE")]
                    [#assign SERVICE2_CHAR1_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR2_PROP_INDICATE")]
                    [#assign SERVICE2_CHAR2_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR3_PROP_INDICATE")]
                    [#assign SERVICE2_CHAR3_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR4_PROP_INDICATE")]
                    [#assign SERVICE2_CHAR4_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE2_CHAR5_PROP_INDICATE")]
                    [#assign SERVICE2_CHAR5_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR1_PROP_INDICATE")]
                    [#assign SERVICE3_CHAR1_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR2_PROP_INDICATE")]
                    [#assign SERVICE3_CHAR2_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR3_PROP_INDICATE")]
                    [#assign SERVICE3_CHAR3_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR4_PROP_INDICATE")]
                    [#assign SERVICE3_CHAR4_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE3_CHAR5_PROP_INDICATE")]
                    [#assign SERVICE3_CHAR5_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR1_PROP_INDICATE")]
                    [#assign SERVICE4_CHAR1_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR2_PROP_INDICATE")]
                    [#assign SERVICE4_CHAR2_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR3_PROP_INDICATE")]
                    [#assign SERVICE4_CHAR3_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR4_PROP_INDICATE")]
                    [#assign SERVICE4_CHAR4_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE4_CHAR5_PROP_INDICATE")]
                    [#assign SERVICE4_CHAR5_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR1_PROP_INDICATE")]
                    [#assign SERVICE5_CHAR1_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR2_PROP_INDICATE")]
                    [#assign SERVICE5_CHAR2_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR3_PROP_INDICATE")]
                    [#assign SERVICE5_CHAR3_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR4_PROP_INDICATE")]
                    [#assign SERVICE5_CHAR4_PROP_INDICATE = definition.value]
                [/#if]
                [#if (definition.name == "SERVICE5_CHAR5_PROP_INDICATE")]
                    [#assign SERVICE5_CHAR5_PROP_INDICATE = definition.value]
                [/#if]

            [/#if]

        [/#list]
    [/#if]
[/#list]

[#assign SERVICES_NUMBER_OF_CHARACTERISTICS = {
  "1":SERVICE1_NUMBER_OF_CHARACTERISTICS,
  "2":SERVICE2_NUMBER_OF_CHARACTERISTICS,
  "3":SERVICE3_NUMBER_OF_CHARACTERISTICS,
  "4":SERVICE4_NUMBER_OF_CHARACTERISTICS,
  "5":SERVICE5_NUMBER_OF_CHARACTERISTICS
}]

[#assign item = 0]
[#assign item_NAME_START = item]
[#assign item_LONG_NAME = item][#assign item = item + 1]
[#assign item_SHORT_NAME = item]
[#assign item_NAME_END = item]

[#assign SERVICES_NAMES = {
  "1":[SERVICE1_LONG_NAME, SERVICE1_SHORT_NAME],
  "2":[SERVICE2_LONG_NAME, SERVICE2_SHORT_NAME],
  "3":[SERVICE3_LONG_NAME, SERVICE3_SHORT_NAME],
  "4":[SERVICE4_LONG_NAME, SERVICE4_SHORT_NAME],
  "5":[SERVICE5_LONG_NAME, SERVICE5_SHORT_NAME]
}]

[#assign SERVICES_CHARS_NAMES = {
  "1":{"1":[SERVICE1_CHAR1_LONG_NAME, SERVICE1_CHAR1_SHORT_NAME],
       "2":[SERVICE1_CHAR2_LONG_NAME, SERVICE1_CHAR2_SHORT_NAME],
       "3":[SERVICE1_CHAR3_LONG_NAME, SERVICE1_CHAR3_SHORT_NAME],
       "4":[SERVICE1_CHAR4_LONG_NAME, SERVICE1_CHAR4_SHORT_NAME],
       "5":[SERVICE1_CHAR5_LONG_NAME, SERVICE1_CHAR5_SHORT_NAME]},
  "2":{"1":[SERVICE2_CHAR1_LONG_NAME, SERVICE2_CHAR1_SHORT_NAME],
       "2":[SERVICE2_CHAR2_LONG_NAME, SERVICE2_CHAR2_SHORT_NAME],
       "3":[SERVICE2_CHAR3_LONG_NAME, SERVICE2_CHAR3_SHORT_NAME],
       "4":[SERVICE2_CHAR4_LONG_NAME, SERVICE2_CHAR4_SHORT_NAME],
       "5":[SERVICE2_CHAR5_LONG_NAME, SERVICE2_CHAR5_SHORT_NAME]},
  "3":{"1":[SERVICE3_CHAR1_LONG_NAME, SERVICE3_CHAR1_SHORT_NAME],
       "2":[SERVICE3_CHAR2_LONG_NAME, SERVICE3_CHAR2_SHORT_NAME],
       "3":[SERVICE3_CHAR3_LONG_NAME, SERVICE3_CHAR3_SHORT_NAME],
       "4":[SERVICE3_CHAR4_LONG_NAME, SERVICE3_CHAR4_SHORT_NAME],
       "5":[SERVICE3_CHAR5_LONG_NAME, SERVICE3_CHAR5_SHORT_NAME]},
  "4":{"1":[SERVICE4_CHAR1_LONG_NAME, SERVICE4_CHAR1_SHORT_NAME],
       "2":[SERVICE4_CHAR2_LONG_NAME, SERVICE4_CHAR2_SHORT_NAME],
       "3":[SERVICE4_CHAR3_LONG_NAME, SERVICE4_CHAR3_SHORT_NAME],
       "4":[SERVICE4_CHAR4_LONG_NAME, SERVICE4_CHAR4_SHORT_NAME],
       "5":[SERVICE4_CHAR5_LONG_NAME, SERVICE4_CHAR5_SHORT_NAME]},
  "5":{"1":[SERVICE5_CHAR1_LONG_NAME, SERVICE5_CHAR1_SHORT_NAME],
       "2":[SERVICE5_CHAR2_LONG_NAME, SERVICE5_CHAR2_SHORT_NAME],
       "3":[SERVICE5_CHAR3_LONG_NAME, SERVICE5_CHAR3_SHORT_NAME],
       "4":[SERVICE5_CHAR4_LONG_NAME, SERVICE5_CHAR4_SHORT_NAME],
       "5":[SERVICE5_CHAR5_LONG_NAME, SERVICE5_CHAR5_SHORT_NAME]}
}]

[#assign SERVICES_CHARS_VALUE_LENGTH = {
  "1":{"1":SERVICE1_CHAR1_VALUE_LENGTH,
       "2":SERVICE1_CHAR2_VALUE_LENGTH,
       "3":SERVICE1_CHAR3_VALUE_LENGTH,
       "4":SERVICE1_CHAR4_VALUE_LENGTH,
       "5":SERVICE1_CHAR5_VALUE_LENGTH},
  "2":{"1":SERVICE2_CHAR1_VALUE_LENGTH,
       "2":SERVICE2_CHAR2_VALUE_LENGTH,
       "3":SERVICE2_CHAR3_VALUE_LENGTH,
       "4":SERVICE2_CHAR4_VALUE_LENGTH,
       "5":SERVICE2_CHAR5_VALUE_LENGTH},
  "3":{"1":SERVICE3_CHAR1_VALUE_LENGTH,
       "2":SERVICE3_CHAR2_VALUE_LENGTH,
       "3":SERVICE3_CHAR3_VALUE_LENGTH,
       "4":SERVICE3_CHAR4_VALUE_LENGTH,
       "5":SERVICE3_CHAR5_VALUE_LENGTH},
  "4":{"1":SERVICE4_CHAR1_VALUE_LENGTH,
       "2":SERVICE4_CHAR2_VALUE_LENGTH,
       "3":SERVICE4_CHAR3_VALUE_LENGTH,
       "4":SERVICE4_CHAR4_VALUE_LENGTH,
       "5":SERVICE4_CHAR5_VALUE_LENGTH},
  "5":{"1":SERVICE5_CHAR1_VALUE_LENGTH,
       "2":SERVICE5_CHAR2_VALUE_LENGTH,
       "3":SERVICE5_CHAR3_VALUE_LENGTH,
       "4":SERVICE5_CHAR4_VALUE_LENGTH,
       "5":SERVICE5_CHAR5_VALUE_LENGTH}
}]

[#assign item = 0]
[#assign item_PROP_START = item]
[#-- assign item_PROP_NONE = item][#assign item = item + 1--]
[#assign item_PROP_BROADCAST = item][#assign item = item + 1]
[#assign item_PROP_READ = item][#assign item = item + 1]
[#assign item_PROP_WRITE_WITHOUT_RESP = item][#assign item = item + 1]
[#assign item_PROP_WRITE = item][#assign item = item + 1]
[#assign item_PROP_NOTIFY = item][#assign item = item + 1]
[#assign item_PROP_INDICATE = item][#-- assign item++]
[#assign item_PROP_SIGNED_WRITE = item][#assign item++]
[# assign item_PROP_EXT = item --]
[#assign item_PROP_END = item]

[#assign SERVICES_CHARS_PROP = {
  "1":{"1":[SERVICE1_CHAR1_PROP_BROADCAST, SERVICE1_CHAR1_PROP_READ, SERVICE1_CHAR1_PROP_WRITE_WITHOUT_RESP, SERVICE1_CHAR1_PROP_WRITE, SERVICE1_CHAR1_PROP_NOTIFY, SERVICE1_CHAR1_PROP_INDICATE],
       "2":[SERVICE1_CHAR2_PROP_BROADCAST, SERVICE1_CHAR2_PROP_READ, SERVICE1_CHAR2_PROP_WRITE_WITHOUT_RESP, SERVICE1_CHAR2_PROP_WRITE, SERVICE1_CHAR2_PROP_NOTIFY, SERVICE1_CHAR2_PROP_INDICATE],
       "3":[SERVICE1_CHAR3_PROP_BROADCAST, SERVICE1_CHAR3_PROP_READ, SERVICE1_CHAR3_PROP_WRITE_WITHOUT_RESP, SERVICE1_CHAR3_PROP_WRITE, SERVICE1_CHAR3_PROP_NOTIFY, SERVICE1_CHAR3_PROP_INDICATE],
       "4":[SERVICE1_CHAR4_PROP_BROADCAST, SERVICE1_CHAR4_PROP_READ, SERVICE1_CHAR4_PROP_WRITE_WITHOUT_RESP, SERVICE1_CHAR4_PROP_WRITE, SERVICE1_CHAR4_PROP_NOTIFY, SERVICE1_CHAR4_PROP_INDICATE],
       "5":[SERVICE1_CHAR5_PROP_BROADCAST, SERVICE1_CHAR5_PROP_READ, SERVICE1_CHAR5_PROP_WRITE_WITHOUT_RESP, SERVICE1_CHAR5_PROP_WRITE, SERVICE1_CHAR5_PROP_NOTIFY, SERVICE1_CHAR5_PROP_INDICATE]},
  "2":{"1":[SERVICE2_CHAR1_PROP_BROADCAST, SERVICE2_CHAR1_PROP_READ, SERVICE2_CHAR1_PROP_WRITE_WITHOUT_RESP, SERVICE2_CHAR1_PROP_WRITE, SERVICE2_CHAR1_PROP_NOTIFY, SERVICE2_CHAR1_PROP_INDICATE],
       "2":[SERVICE2_CHAR2_PROP_BROADCAST, SERVICE2_CHAR2_PROP_READ, SERVICE2_CHAR2_PROP_WRITE_WITHOUT_RESP, SERVICE2_CHAR2_PROP_WRITE, SERVICE2_CHAR2_PROP_NOTIFY, SERVICE2_CHAR2_PROP_INDICATE],
       "3":[SERVICE2_CHAR3_PROP_BROADCAST, SERVICE2_CHAR3_PROP_READ, SERVICE2_CHAR3_PROP_WRITE_WITHOUT_RESP, SERVICE2_CHAR3_PROP_WRITE, SERVICE2_CHAR3_PROP_NOTIFY, SERVICE2_CHAR3_PROP_INDICATE],
       "4":[SERVICE2_CHAR4_PROP_BROADCAST, SERVICE2_CHAR4_PROP_READ, SERVICE2_CHAR4_PROP_WRITE_WITHOUT_RESP, SERVICE2_CHAR4_PROP_WRITE, SERVICE2_CHAR4_PROP_NOTIFY, SERVICE2_CHAR4_PROP_INDICATE],
       "5":[SERVICE2_CHAR5_PROP_BROADCAST, SERVICE2_CHAR5_PROP_READ, SERVICE2_CHAR5_PROP_WRITE_WITHOUT_RESP, SERVICE2_CHAR5_PROP_WRITE, SERVICE2_CHAR5_PROP_NOTIFY, SERVICE2_CHAR5_PROP_INDICATE]},
  "3":{"1":[SERVICE3_CHAR1_PROP_BROADCAST, SERVICE3_CHAR1_PROP_READ, SERVICE3_CHAR1_PROP_WRITE_WITHOUT_RESP, SERVICE3_CHAR1_PROP_WRITE, SERVICE3_CHAR1_PROP_NOTIFY, SERVICE3_CHAR1_PROP_INDICATE],
       "2":[SERVICE3_CHAR2_PROP_BROADCAST, SERVICE3_CHAR2_PROP_READ, SERVICE3_CHAR2_PROP_WRITE_WITHOUT_RESP, SERVICE3_CHAR2_PROP_WRITE, SERVICE3_CHAR2_PROP_NOTIFY, SERVICE3_CHAR2_PROP_INDICATE],
       "3":[SERVICE3_CHAR3_PROP_BROADCAST, SERVICE3_CHAR3_PROP_READ, SERVICE3_CHAR3_PROP_WRITE_WITHOUT_RESP, SERVICE3_CHAR3_PROP_WRITE, SERVICE3_CHAR3_PROP_NOTIFY, SERVICE3_CHAR3_PROP_INDICATE],
       "4":[SERVICE3_CHAR4_PROP_BROADCAST, SERVICE3_CHAR4_PROP_READ, SERVICE3_CHAR4_PROP_WRITE_WITHOUT_RESP, SERVICE3_CHAR4_PROP_WRITE, SERVICE3_CHAR4_PROP_NOTIFY, SERVICE3_CHAR4_PROP_INDICATE],
       "5":[SERVICE3_CHAR5_PROP_BROADCAST, SERVICE3_CHAR5_PROP_READ, SERVICE3_CHAR5_PROP_WRITE_WITHOUT_RESP, SERVICE3_CHAR5_PROP_WRITE, SERVICE3_CHAR5_PROP_NOTIFY, SERVICE3_CHAR5_PROP_INDICATE]},
  "4":{"1":[SERVICE4_CHAR1_PROP_BROADCAST, SERVICE4_CHAR1_PROP_READ, SERVICE4_CHAR1_PROP_WRITE_WITHOUT_RESP, SERVICE4_CHAR1_PROP_WRITE, SERVICE4_CHAR1_PROP_NOTIFY, SERVICE4_CHAR1_PROP_INDICATE],
       "2":[SERVICE4_CHAR2_PROP_BROADCAST, SERVICE4_CHAR2_PROP_READ, SERVICE4_CHAR2_PROP_WRITE_WITHOUT_RESP, SERVICE4_CHAR2_PROP_WRITE, SERVICE4_CHAR2_PROP_NOTIFY, SERVICE4_CHAR2_PROP_INDICATE],
       "3":[SERVICE4_CHAR3_PROP_BROADCAST, SERVICE4_CHAR3_PROP_READ, SERVICE4_CHAR3_PROP_WRITE_WITHOUT_RESP, SERVICE4_CHAR3_PROP_WRITE, SERVICE4_CHAR3_PROP_NOTIFY, SERVICE4_CHAR3_PROP_INDICATE],
       "4":[SERVICE4_CHAR4_PROP_BROADCAST, SERVICE4_CHAR4_PROP_READ, SERVICE4_CHAR4_PROP_WRITE_WITHOUT_RESP, SERVICE4_CHAR4_PROP_WRITE, SERVICE4_CHAR4_PROP_NOTIFY, SERVICE4_CHAR4_PROP_INDICATE],
       "5":[SERVICE4_CHAR5_PROP_BROADCAST, SERVICE4_CHAR5_PROP_READ, SERVICE4_CHAR5_PROP_WRITE_WITHOUT_RESP, SERVICE4_CHAR5_PROP_WRITE, SERVICE4_CHAR5_PROP_NOTIFY, SERVICE4_CHAR5_PROP_INDICATE]},
  "5":{"1":[SERVICE5_CHAR1_PROP_BROADCAST, SERVICE5_CHAR1_PROP_READ, SERVICE5_CHAR1_PROP_WRITE_WITHOUT_RESP, SERVICE5_CHAR1_PROP_WRITE, SERVICE5_CHAR1_PROP_NOTIFY, SERVICE5_CHAR1_PROP_INDICATE],
       "2":[SERVICE5_CHAR2_PROP_BROADCAST, SERVICE5_CHAR2_PROP_READ, SERVICE5_CHAR2_PROP_WRITE_WITHOUT_RESP, SERVICE5_CHAR2_PROP_WRITE, SERVICE5_CHAR2_PROP_NOTIFY, SERVICE5_CHAR2_PROP_INDICATE],
       "3":[SERVICE5_CHAR3_PROP_BROADCAST, SERVICE5_CHAR3_PROP_READ, SERVICE5_CHAR3_PROP_WRITE_WITHOUT_RESP, SERVICE5_CHAR3_PROP_WRITE, SERVICE5_CHAR3_PROP_NOTIFY, SERVICE5_CHAR3_PROP_INDICATE],
       "4":[SERVICE5_CHAR4_PROP_BROADCAST, SERVICE5_CHAR4_PROP_READ, SERVICE5_CHAR4_PROP_WRITE_WITHOUT_RESP, SERVICE5_CHAR4_PROP_WRITE, SERVICE5_CHAR4_PROP_NOTIFY, SERVICE5_CHAR4_PROP_INDICATE],
       "5":[SERVICE5_CHAR5_PROP_BROADCAST, SERVICE5_CHAR5_PROP_READ, SERVICE5_CHAR5_PROP_WRITE_WITHOUT_RESP, SERVICE5_CHAR5_PROP_WRITE, SERVICE5_CHAR5_PROP_NOTIFY, SERVICE5_CHAR5_PROP_INDICATE]}
}]

[#assign SERVICES_CHARS_SUFFIX = ["", "_READ_EVT", "_WRITE_NO_RESP_EVT", "_WRITE_EVT", "_NOTIFY_ENABLED_EVT", "_INDICATE_ENABLED_EVT"]]

[#macro customServChar service characteristic]
    CUSTOM_STM_${SERVICES_CHARS_NAMES[service?string][characteristic?string][item_SHORT_NAME]?upper_case}[#t]
[/#macro]

[#macro customEventCode item service characteristic]
    [#if SERVICES_CHARS_SUFFIX[item] != ""]
  [@customServChar service characteristic/]${SERVICES_CHARS_SUFFIX[item]},
        [#if SERVICES_CHARS_SUFFIX[item]?contains("ENABLED")]
  [@customServChar service characteristic/]${SERVICES_CHARS_SUFFIX[item]?replace("ENABLED","DISABLED")},
        [/#if]
    [/#if]
[/#macro]

[#macro capitalizeWords words]
    [#list words as word]
        ${word?capitalize}[#t]
    [/#list]
[/#macro]

[#macro characteristicShortNameCapitalized service characteristic]
    [@capitalizeWords SERVICES_CHARS_NAMES[service?string][characteristic?string][item_SHORT_NAME]?matches(r"[a-zA-Z]+\d*[^a-zA-Z]*")/]
[/#macro]

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __CUSTOM_STM_H
#define __CUSTOM_STM_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
typedef enum
{
[#if NUMBER_OF_SERVICES != "0"]
    [#list 1..NUMBER_OF_SERVICES?number as service]
  /* ${SERVICES_NAMES[service?string][item_LONG_NAME]} */
        [#list 1..SERVICES_NUMBER_OF_CHARACTERISTICS[service?string]?number as characteristic]
  [@customServChar service characteristic/],
        [/#list]
    [/#list]
[/#if]
} Custom_STM_Char_Opcode_t;

typedef enum
{
[#if NUMBER_OF_SERVICES != "0"]
    [#list 1..NUMBER_OF_SERVICES?number as service]
        [#list 1..SERVICES_NUMBER_OF_CHARACTERISTICS[service?string]?number as characteristic]
  /* ${SERVICES_CHARS_NAMES[service?string][characteristic?string][item_LONG_NAME]} */
            [#list item_PROP_START..item_PROP_END as item]
                [#if SERVICES_CHARS_PROP[service?string][characteristic?string][item]?? &&
                        SERVICES_CHARS_PROP[service?string][characteristic?string][item] != ""]
                    [@customEventCode item service characteristic /]
                [/#if]
            [/#list]
        [/#list]
    [/#list]
[/#if]

  CUSTOM_STM_BOOT_REQUEST_EVT
} Custom_STM_Opcode_evt_t;

typedef struct
{
  uint8_t * pPayload;
  uint8_t   Length;
} Custom_STM_Data_t;

typedef struct
{
  Custom_STM_Opcode_evt_t       Custom_Evt_Opcode;
  Custom_STM_Data_t             DataTransfered;
  uint16_t                      ConnectionHandle;
  uint8_t                       ServiceInstance;
} Custom_STM_App_Notification_evt_t;

/* USER CODE BEGIN ET */

/* USER CODE END ET */


/* Exported constants --------------------------------------------------------*/
[#if NUMBER_OF_SERVICES != "0"]
    [#list 1..NUMBER_OF_SERVICES?number as service]
        [#list 1..SERVICES_NUMBER_OF_CHARACTERISTICS[service?string]?number as characteristic]
extern uint8_t Size[@characteristicShortNameCapitalized service characteristic/];
        [/#list]
    [/#list]
[/#if]

/* USER CODE BEGIN EC */

/* USER CODE END EC */

/* External variables --------------------------------------------------------*/
/* USER CODE BEGIN EV */

/* USER CODE END EV */

/* Exported macros -----------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions ------------------------------------------------------- */
void SVCCTL_InitCustomSvc(void);
void Custom_STM_App_Notification(Custom_STM_App_Notification_evt_t *pNotification);
tBleStatus Custom_STM_App_Update_Char(Custom_STM_Char_Opcode_t CharOpcode,  uint8_t *pPayload);
/* USER CODE BEGIN EF */

/* USER CODE END EF */


#ifdef __cplusplus
}
#endif

#endif /*__CUSTOM_STM_H */
