[#ftl]

[#assign coreDir=""]

[#assign coreDir=sourceDir]
/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     ${date}
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "${FamilyName?lower_case}xx_hal.h"

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
}