[#ftl]

[#assign coreDir=""]

[#assign coreDir=sourceDir]
/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     ${date}
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
[#if FamilyName="STM32WB0" || FamilyName="STM32WL3"]
#include "${FamilyName?lower_case}x_hal.h"
[#else]
#include "${FamilyName?lower_case}xx_hal.h"
[/#if]

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
}