[#ftl]

[#--STM32-RPROC binding--]
[#--///////////////////--]

[#macro bind_stm32_rproc	pElmt pDtLevel]
[#compress]
[#local TABres = dts_get_tabs(pDtLevel)]
[#local TABnode = TABres.TABN]
[#local TABres = dts_get_tabs(pDtLevel+1)]
[#local TABsubnode = TABres.TABN]
[#local TABsubprop = TABres.TABP]
[#local deviceFwName = srvcmx_getFwNameOfBindedDevice_inDTS("ipcc1")]
[/#compress]
[#t]
	[#if srvcmx_isDeviceEnabled("ipcc1") && deviceFwName?has_content]
${TABnode}/*Restriction: "memory-region" property is not managed - please to use User-Section if needed*/
	[/#if]
[#t]
	[#if srvcmx_isDeviceEnabled("ipcc1") && deviceFwName?has_content]
${TABnode}mboxes = [#t]
		[#if srvcmx_isDeviceEnabled("openamp")]
		 	[#if srvcmx_isDeviceEnabled("usbpd")]
<&ipcc1 0x100>, <&ipcc1 0x101>, [#t]
			[#else]
<&ipcc1 0>, <&ipcc1 1>, [#t]
			[/#if]
		[/#if]
<&ipcc1 2>;
${TABnode}mbox-names = [#t]
		[#if srvcmx_isDeviceEnabled("openamp")]
"vq0", "vq1", [#t]
		[/#if]
"shutdown";
	[/#if]
[#t]
#n
[#t]
	[#--binding for "Documentation/bindings/remoteproc/rproc-srm.txt"--]
[/#macro]
