[#ftl]

[#--STM32-OMMANAGER binding--]
[#--///////////////////--]

[#macro bind_stm32_ommanager	pElmt pDtLevel]
[#compress]
[#local TABres = dts_get_tabs(pDtLevel)]
[#local TABnode = TABres.TABN]
[#local TABres = dts_get_tabs(pDtLevel+1)]
[#local TABsubnode = TABres.TABN]
[#local TABsubprop = TABres.TABP]
[#local UiRegionName_Index = 2]
[#local UiRegionSize_Index = 4]
[#local RegionNameList = []]
[#local MemoryRegion = ""]
[#local MemoryRegionName = ""]

[#list mx_RIF_Params.entrySet() as RIF_Params]
			[#if (RIF_Params.key)?? && RIF_Params.key == "risaf2"]
				[#local BKPSRAMTable = RIF_Params.value]
					[#list BKPSRAMTable.entrySet() as RISAFTable_params]
						[#local RegionName= RISAFTable_params.value[UiRegionName_Index]]
						[#local RegionNameMap= srvc_str_toMap(RegionName)]
						[#local RegionSize= RISAFTable_params.value[UiRegionSize_Index]]
						[#local RegionSizeMap= srvc_str_toMap(RegionSize)]
						[#list RegionNameMap?keys as RegionNameKey]
							[#if RegionNameMap[RegionNameKey]!=""]
							[#local RegionNameList=RegionNameList+[RegionNameMap[RegionNameKey]]]
								[#list RegionSizeMap?keys as RegionSizeKey]
									[#if RegionSizeMap[RegionSizeKey]!="0x0" ]
									[#local MemoryRegion = MemoryRegion + "<&"+RegionNameMap[RegionNameKey]?trim?replace("-","_")?lower_case+">, " ]
									[#local MemoryRegionName = MemoryRegionName +RegionNameMap[RegionNameKey]?trim?replace("-","_")?lower_case+", " ]
									[/#if]
								[/#list]
							[/#if]
						[/#list]
					[/#list]
			[/#if]
[/#list]
[/#compress]
[#t]
${TABnode}memory-region = ${MemoryRegion?keep_before_last(",")+";"}
${TABnode}memory-region-names = "${MemoryRegionName?keep_before_last(",")+"\";"}
[#t]
[/#macro]
