[#ftl]
[#assign name = "ip"]
[#assign variables = " "]
[#if IPdatas??]
[#list IPdatas as IP]
[#-- Global variables --]
[#if IP.variables??]
[#list IP.variables as variable]
    [#if !variables?contains(variable.value + " " + variable.name)]
extern ${variable.value} ${variable.name};
[#assign variables = variables + " " + variable.value + " " + variable.name]
            [/#if]
[/#list]
[/#if]
[#-- Add global dma Handler --]
[#list IP.configModelList as instanceData]
    [#if instanceData.dmaHandel??]
        [#list instanceData.dmaHandel as dHandle]
            [#if !variables?contains(dHandle)]
extern ${dHandle};
[#assign variables = variables + " " + dHandle]
            [/#if]
        [/#list]
    [/#if]
[/#list]
[/#list]
[/#if]
[#-- Global variables --]