[#ftl]
[#assign SIGFOX_APP_MEM_POOL_SIZE = "6144"]
[#if SWIPdatas??]
    [#list SWIPdatas as SWIP]
        [#if SWIP.defines??]
            [#list SWIP.defines as definition]
                [#if definition.name == "SIGFOX_APP_MEM_POOL_SIZE"]
                    [#assign SIGFOX_APP_MEM_POOL_SIZE = definition.value]
                [/#if]
            [/#list]
        [/#if]
    [/#list]
[/#if]

#define SIGFOX_APP_MEM_POOL_SIZE                 ${SIGFOX_APP_MEM_POOL_SIZE}