[#ftl]
[#list SWIPdatas as SWIP]
    [#assign instName = SWIP.ipName]
    [#assign fileName = SWIP.fileName]
    [#assign version = SWIP.version]

    [#if SWIP.defines??]
        [#list SWIP.defines as definition]
            [#if definition.name=="LD1"]
                [#assign LED1 = definition.value]
            [/#if]
            [#if definition.name=="LD2"]
                [#assign LED2 = definition.value]
            [/#if]
            [#if definition.name=="LD3"]
                [#assign LED3 = definition.value]
            [/#if]
            [#if definition.name=="LD4"]
                [#assign LED4 = definition.value]
            [/#if]
            [#if definition.name=="BUTTON"]
                [#assign BUTTON = definition.value]
            [/#if]
			[#if definition.name=="BUTTON2"]
                [#assign BUTTON2 = definition.value]
            [/#if]
			[#if definition.name=="BUTTON3"]
                [#assign BUTTON3 = definition.value]
            [/#if]
			[#if definition.name=="BUTTON4"]
                [#assign BUTTON4 = definition.value]
            [/#if]
            [#if definition.name=="VCP"]
                [#assign VCP = definition.value]
            [/#if]
            [#if definition.name=="Bsp_Common_DEMO"]
                [#assign Bsp_Common_DEMO = definition.value]
            [/#if]
        [/#list]
    [/#if]
[/#list]
[#compress]
[#if Bsp_Common_DEMO?? && Bsp_Common_DEMO == "true"]
	#t/* USER CODE BEGIN BSP */
	[#if VCP == "true"]
	    #n#t/* -- Sample board code to send message over COM1 port ---- */
	    [#if contextFolder?? && contextFolder?contains("Appli")]
            #tprintf("Welcome to STM32 world !\n\rApplication project is running...\n\r");
        [/#if]
        [#if contextFolder?? && contextFolder?contains("FSBL")]
            #tprintf("Welcome to STM32 world !\n\rBoot project is running...\n\r");
        [/#if]
	[/#if]
	[#if (LED1??&& LED1=="true") || (LED2??&& LED2=="true") || (LED3??&& LED3=="true") || (LED4??&& LED4=="true") ]
		#n#t/* -- Sample board code to switch on leds ---- */

        [#if  LED1?? && LED1 == "true"]
			#tBSP_LED_On(LED_BLUE);
		[/#if]
		 [#if  LED2?? && LED2 == "true"]
			#tBSP_LED_On(LED_RED);
		[/#if]
		[#if  LED3?? && LED3 == "true"]
			#tBSP_LED_On(LED_GREEN);
		[/#if]
		
	[/#if] 
	#n#t/* USER CODE END BSP */
[/#if]
[/#compress]
